all:
	g++ prueba.cpp -o main.o

#g++ -o news.o news.cpp -lcurl
#g++ -o Main.o Main.cpp -lcurl
# docker run -it --rm -v C:\Users\santi\OneDrive\Desktop\TEC-UCR\TEC\II-Semestre\Estructuras\Caso1:/home gcc bash