all:
	g++ Main.cpp -o Main.o

list: 
	g++ CircularLinkedList.cpp -o CircularLinkedList.o

news:
	g++ News.cpp -o News.o

main:
	g++ -o Main.o Main.cpp -lcurl

#g++ -o news.o news.cpp -lcurl
#g++ -o Main.o Main.cpp -lcurl
# docker run -it --rm -v C:\Users\santi\OneDrive\Desktop\TEC-UCR\TEC\II-Semestre\Estructuras\Caso1:/home gcc bash